//Created By Rabia Alhaffar In 20/April/2019
var FB_GetPlayerID = () => FBInstant.player.getID();
var FB_GetPlayerName = () => FBInstant.player.getName();
var FB_GetPlayerPhoto = () => FBInstant.player.getPhoto();	
var FB_GetContextID = () => FBInstant.context.getID();
var FB_GetContextType = () => FBInstant.context.getType();
var FB_Get_OS = () => FBInstant.getPlatform();
var FB_Get_SDK_Version = () => FBInstant.getSDKVersion();
var FB_Get_Localization = () => FBInstant.getLocale();
var FB_SetProgress = (x) => FBInstant.setLoadingProgress(x);
var FB_ExitGame = () => FBInstant.quit();
var FB_Get_APIS = () => FBInstant.getSupportedAPIs();
var FB_GetLeaderboardName = () => FBInstant.leaderboard.getName();
var FB_PostScore = (x) => FBInstant.postSessionScore(x);